import fs from 'fs';
import path from 'path';

// Products parsed from the official indexed prompt
const rawProducts = [
  {
    id: "projeto_db8j8hjjhzl",
    titulo: "Macacão longo",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão longo, em tons de roxo e marrom.",
    descricao_comercial: "A imagem apresenta macacão longo, com peça única, cor roxa predominante, acabamento visual superior franzido e faixa larga na cintura. A composição visual utiliza tons de roxo e marrom.",
    imagens: ["instagram/Db8j8HJJhZL/01.webp"],
    palavras_chave: ["Roupas Femininas", "roxo", "marrom", "macacão", "macacão longo", "moda feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_db8jjqduyie",
    titulo: "Conjunto de cropped e calça",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de cropped e calça, em tons de marrom e branco.",
    descricao_comercial: "A imagem apresenta conjunto de cropped e calça, com cor principal marrom, detalhes com debrum branco, alças finas no cropped e calça comprida. A composição visual utiliza tons de marrom e branco.",
    imagens: ["instagram/Db8jJqduyIe/01.webp"],
    palavras_chave: ["Marrom", "Roupas Femininas", "Branco", "conjunto feminino", "cropped", "calça", "moda feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_db8jnvwpvou",
    titulo: "Conjunto de cropped e calça alfaiataria",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de cropped e calça, em tons de bege e dourado.",
    descricao_comercial: "A imagem apresenta conjunto de cropped e calça, com conjunto monocromático em tom bege, cropped com botões frontais e gola estilo blazer, calça de pernas compridas com costura frontal visível e mangas longas bufantes com punhos ajustados.",
    imagens: ["instagram/Db8jnVWPvoU/01.webp"],
    palavras_chave: ["bege", "Roupas Femininas", "dourado", "conjunto feminino", "cropped", "calça", "moda feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dc6s5ldptlk",
    titulo: "Banner promocional de vestidos",
    categoria: "Promoções",
    ambiente: "Não determinado",
    descricao_curta: "Banner promocional, em tons de azul e branco.",
    descricao_comercial: "O conjunto de 2 imagens apresenta banner promocional por diferentes enquadramentos, com fundo azul liso, texto em letras maiúsculas brancas, presença de emoji em formato de mão e texto centralizado em letras maiúsculas brancas.",
    imagens: ["instagram/Dc6S5LdpTlK/01.webp", "instagram/Dc6TYYaM-qT/01.webp"],
    palavras_chave: ["Promoções", "azul", "branco", "promoção", "vestidos", "desconto", "moda", "oferta"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dc6thsbb1xp",
    titulo: "Anúncio de Promoção",
    categoria: "Promoções",
    ambiente: "Não determinado",
    descricao_curta: "Anúncio de Promoção, em tons de amarelo e branco.",
    descricao_comercial: "A imagem apresenta anúncio de promoção, com fundo com cor sólida, texto centralizado em letras maiúsculas e presença de caracteres numéricos indicando desconto e data.",
    imagens: ["instagram/Dc6THsBB1xp/01.webp"],
    palavras_chave: ["Promoções", "Amarelo", "Branco", "promoção", "desconto", "vestidos", "aviso"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcekhs0brm9",
    titulo: "Vestido midi de manga longa",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido midi de manga longa, em tons de marrom, branco e terracota.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido midi de manga longa por diferentes enquadramentos, com mangas longas, decote em v, comprimento midi e textura canelada na parte superior e mangas.",
    imagens: ["instagram/DceKhS0Brm9/01.webp", "instagram/DceKIkRNNg9/01.webp"],
    palavras_chave: ["Vestidos", "marrom", "branco", "vestido", "manga longa", "moda feminina", "terracota", "vestido midi", "decote em v"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dcekwybto0k",
    titulo: "Vestido de manga longa com textura",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido de manga longa com textura, em tons de marrom claro e bege.",
    descricao_comercial: "A imagem apresenta vestido de manga longa com textura, com comprimento midi, mangas longas e gola redonda.",
    imagens: ["instagram/DceKWybtO0k/01.webp"],
    palavras_chave: ["Vestidos", "marrom claro", "bege", "vestido", "vestido midi", "manga longa", "moda feminina", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcotedoptlv",
    titulo: "Blusa feminina com gola laço e saia",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Blusa feminina com gola laço e saia, em tons de amarelo, rosa e rosa claro.",
    descricao_comercial: "O conjunto de 2 imagens apresenta blusa feminina com gola laço e saia por diferentes enquadramentos, com blusa rosa claro com mangas longas e punhos franzidos, gola alta com amarração em laço frontal, saia amarela com textura franzida na cintura.",
    imagens: ["instagram/DcOtEdOPTLV/01.webp", "instagram/DcOtMq2ANj7/01.webp"],
    palavras_chave: ["Moda Feminina", "amarelo", "blusa rosa", "gola laço", "rosa", "saia amarela", "conjunto feminino", "plus size"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dcotiptg_ij",
    titulo: "Blusa Estampada com Laço",
    categoria: "Blusas",
    ambiente: "Não determinado",
    descricao_curta: "Blusa Estampada com Laço, em tons de marrom, preto e amarelo claro.",
    descricao_comercial: "A imagem apresenta blusa estampada com laço, com estampa animal print com manchas escuras, gola com amarração em laço, mangas longas bufantes e punhos franzidos com elástico.",
    imagens: ["instagram/DcOtIptg-Ij/01.webp"],
    palavras_chave: ["Blusas", "marrom", "preto", "amarelo claro", "blusa", "feminina", "animal print", "onça", "manga longa", "laço"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcre2kqpm0b",
    titulo: "Calça com estampa floral e botões frontais",
    categoria: "Calças",
    ambiente: "Não determinado",
    descricao_curta: "Calça com estampa floral e botões frontais, em tons de rosa, laranja e bege.",
    descricao_comercial: "A imagem apresenta calça com estampa floral e botões frontais, com calça de cor rosa, estampa floral em tons de laranja, dois botões visíveis no cós e bolsos frontais.",
    imagens: ["instagram/DcRe2KQpM0b/01.webp"],
    palavras_chave: ["Calças", "rosa", "laranja", "bege", "calça feminina", "calça estampada", "calça floral", "moda feminina", "plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dcre6xup0um",
    titulo: "Calça estampa floral",
    categoria: "Calças",
    ambiente: "Não determinado",
    descricao_curta: "Calça estampa floral, em tons de vermelho e branco.",
    descricao_comercial: "A imagem apresenta calça estampa floral, com estampa floral em tons claros, fundo vermelho e cós franzido.",
    imagens: ["instagram/DcRe6xUp0uM/01.webp"],
    palavras_chave: ["Calças", "vermelho", "branco", "calça", "estampa floral", "moda feminina", "plus size", "casual"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcre9q_p3vd",
    titulo: "Calça Pantalona Estampada",
    categoria: "Calças",
    ambiente: "Não determinado",
    descricao_curta: "Calça Pantalona Estampada, em tons de rosa e laranja.",
    descricao_comercial: "A imagem apresenta calça pantalona estampada, com calça de cor rosa, estampa floral em tons de laranja, cós alto com botões frontais decorativos e bolsos frontais embutidos.",
    imagens: ["instagram/DcRe9q_p3Vd/01.webp"],
    palavras_chave: ["rosa", "laranja", "Calças", "calça", "pantalona", "estampa floral", "moda feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcrfcl5j_a",
    titulo: "Vestido longo sem mangas",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido longo sem mangas, em tons de azul escuro e bege.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido longo sem mangas por diferentes enquadramentos, com sem mangas, modelagem longa, decote redondo e fenda lateral.",
    imagens: ["instagram/DcRfcl5J__A/01.webp", "instagram/DcRfWDOpYGa/01.webp"],
    palavras_chave: ["Azul escuro", "Vestidos", "vestido", "vestido longo", "moda feminina", "plus size", "bege", "vestido sem mangas", "vestido com fenda"],
    confidence: 0.9,
    needs_review: true
  },
  {
    id: "projeto_dcrfdmxpkcm",
    titulo: "Blusa marrom e saia midi azul",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Blusa marrom e saia midi azul, em tons de marrom e azul claro.",
    descricao_comercial: "A imagem apresenta blusa marrom e saia midi azul, com blusa de manga longa com decote em v e detalhe cruzado na frente, saia midi com fenda frontal e bolsos.",
    imagens: ["instagram/DcRfDmXpkcM/01.webp"],
    palavras_chave: ["Roupas Femininas", "marrom", "azul claro", "moda feminina", "blusa marrom", "saia midi", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcrfgplpgrb",
    titulo: "Conjunto de Vestuário Feminino",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Vestuário Feminino, em tons de azul claro, branco e vermelho.",
    descricao_comercial: "A imagem apresenta conjunto de vestuário feminino, com camiseta com estampa frontal em tons de vermelho, saia com lavagem jeans clara e comprimento midi, fenda central na barra da saia.",
    imagens: ["instagram/DcRfGPlpgRb/01.webp"],
    palavras_chave: ["Roupas Femininas", "azul claro", "branco", "vermelho", "moda feminina", "look casual", "saia jeans", "camiseta estampada"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcrfjpajbh7",
    titulo: "Conjunto de Roupa Feminina",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Roupa Feminina, em tons de verde, bege e branco.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de roupa feminina por diferentes enquadramentos, com regata sem mangas com decote arredondado, bermuda com bolsos laterais e cinto fino, bolsa de mão com textura trançada.",
    imagens: ["instagram/DcRfjPAJBH7/01.webp", "instagram/DcRftTUJAjH/01.webp"],
    palavras_chave: ["Roupas Femininas", "verde", "bege", "branco", "bermuda bege", "moda feminina", "look casual", "plus size", "regata verde"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dcrfk21jcgo",
    titulo: "Conjunto de Blusa e Saia",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Saia, em tons de marrom e azul claro.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e saia, com blusa de manga longa na cor marrom com decote em v cruzado, saia azul clara com bolsos frontais e fenda central.",
    imagens: ["instagram/DcRfK21JCGo/01.webp"],
    palavras_chave: ["Moda Feminina", "marrom", "azul claro", "blusa marrom", "saia azul", "look casual", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcrflmppa1p",
    titulo: "Conjunto de Blusa e Shorts",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Shorts, em tons de bege, azul escuro e branco.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e shorts, com blusa com gola redonda, shorts de cintura alta, cinto branco fino com fivela e mangas curtas dobradas.",
    imagens: ["instagram/DcRflMppA1P/01.webp"],
    palavras_chave: ["Roupas Femininas", "bege", "azul escuro", "branco", "roupa feminina", "plus size", "conjunto casual", "shorts", "blusa"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcrfztsjpy2",
    titulo: "Vestido Longo Sem Mangas",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido Longo Sem Mangas, em tons de branco e bege.",
    descricao_comercial: "A imagem apresenta vestido longo sem mangas, com comprimento longo, modelagem sem mangas, fenda frontal na saia e textura com padronagem sutil.",
    imagens: ["instagram/DcRfZTsJPy2/01.webp"],
    palavras_chave: ["Vestidos", "branco", "bege", "vestido longo", "moda feminina", "plus size", "vestido sem mangas", "fenda frontal"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcwhs0lj4ir",
    titulo: "Conjunto cropped e short preto",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto cropped e short preto, em tons de preto.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto cropped e short preto por diferentes enquadramentos, com conjunto de duas peças, cor preta predominante, cropped com alças grossas e detalhes cruzados.",
    imagens: ["instagram/DcWhs0LJ4iR/01.webp", "instagram/DcWiWJ-JeLP/01.webp"],
    palavras_chave: ["preto", "Moda Feminina", "cropped", "short", "conjunto preto", "plus size", "shorts", "conjunto feminino"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_dcwikzgpa_3",
    titulo: "Macacão Curto Feminino Plus Size Vermelho",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Curto Feminino Plus Size Vermelho, em tons de vermelho e branco.",
    descricao_comercial: "A imagem apresenta macacão curto feminino plus size vermelho, com peça única de vestuário na cor vermelha, alças largas, detalhe de tiras cruzadas no busto e botões na região central frontal.",
    imagens: ["instagram/DcWiKzgpa-3/01.webp"],
    palavras_chave: ["vermelho", "Roupas Femininas", "branco", "macacão", "plus size", "feminino", "moda casual"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcwl6_pjp1p",
    titulo: "Biquíni Azul com Babadinhos",
    categoria: "Moda Praia",
    ambiente: "Não determinado",
    descricao_curta: "Biquíni Azul com Babadinhos, em tons de azul e branco.",
    descricao_comercial: "O conjunto de 2 imagens apresenta biquíni azul com babadinhos por diferentes enquadramentos, com cor azul uniforme, top com detalhe franzido e babados nas alças, calcinha com cós franzido.",
    imagens: ["instagram/DcWl6-pJp1p/01.webp", "instagram/DcWmMbSpQmw/01.webp"],
    palavras_chave: ["Moda Praia", "Azul", "Branco", "biquíni", "babados", "conjunto", "conjunto de banho"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dcwlpvijsns",
    titulo: "Conjunto de Blazer e Calça com Estampa Quadrada",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blazer e Calça com Estampa Quadrada, em tons de branco e preto.",
    descricao_comercial: "A imagem apresenta conjunto de blazer e calça com estampa quadrada, com estampa quadriculada miúda em tons de branco e preto, blazer aberto, calça de cintura alta e top cropped preto.",
    imagens: ["instagram/DcWlPviJsNS/01.webp"],
    palavras_chave: ["Roupas Femininas", "branco", "preto", "conjunto feminino", "blazer", "calça", "estampa quadriculada", "moda plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dcwlsr7p72x",
    titulo: "Conjunto de Blazer e Calça Pied-de-Poule",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blazer e Calça, em tons de preto, branco e cinza.",
    descricao_comercial: "A imagem apresenta conjunto de blazer e calça, com estampa padrão pied-de-poule em preto e branco, blazer de mangas longas com bolsos frontais aparentes, calça com bolsos laterais utilitários.",
    imagens: ["instagram/DcWlSr7p72X/01.webp"],
    palavras_chave: ["Roupas Femininas", "Preto", "Branco", "Cinza", "conjunto", "blazer", "calça", "moda feminina", "estampa pied-de-poule"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcwlyifjbzm",
    titulo: "Conjunto alfaiataria xadrez",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto alfaiataria xadrez, em tons de branco, preto e cinza.",
    descricao_comercial: "A imagem apresenta conjunto alfaiataria xadrez, com estampa xadrez, cropped preto canelado, cinto com detalhes metálicos e conjunto de blazer e calça.",
    imagens: ["instagram/DcWlYiFJBZm/01.webp"],
    palavras_chave: ["Moda Feminina", "branco", "preto", "cinza", "conjunto", "blazer", "calça", "xadrez", "cropped"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dcwmchlpsjv",
    titulo: "Maiô feminino poá",
    categoria: "Moda Praia",
    ambiente: "Não determinado",
    descricao_curta: "Maiô feminino, em tons de azul teal, branco e bege.",
    descricao_comercial: "A imagem apresenta maiô feminino, com parte superior com estampa de poá, corpo principal em tom azul teal, faixas horizontais translúcidas na região abdominal e decote em v.",
    imagens: ["instagram/DcWmChLpSjv/01.webp"],
    palavras_chave: ["Moda Praia", "azul teal", "branco", "bege", "maiô", "poá", "roupa feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcws_g_uryy",
    titulo: "Vestido Midi Branco",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido Midi, em tons de branco e bege.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido midi por diferentes enquadramentos, com cor predominante branca, alças finas, comprimento midi e estampa ou bordado em tons claros.",
    imagens: ["instagram/DcWS_G-uryY/01.webp", "instagram/DcWTInsxufX/01.webp"],
    palavras_chave: ["Vestidos", "branco", "bege", "vestido", "vestido midi", "moda feminina", "vestido branco", "casual"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dcwspqhpldd",
    titulo: "Conjunto de cropped e saia com franjas",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de cropped e saia, em tons de marrom e branco.",
    descricao_comercial: "A imagem apresenta conjunto de cropped e saia, com conjunto de duas peças na cor marrom, cropped de manga longa com gola e botões frontais claros, aplicação de franjas brilhantes.",
    imagens: ["instagram/DcWSpQhPlDD/01.webp"],
    palavras_chave: ["marrom", "Roupas Femininas", "branco", "cropped", "saia", "conjunto feminino", "franjas", "moda feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcwsvx_vxnx",
    titulo: "Conjunto de Roupa Feminina Preto com Franjas Brilhantes",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Roupa Feminina Preto com Franjas Brilhantes, em tons de preto e branco.",
    descricao_comercial: "A imagem apresenta conjunto de roupa feminina preto com franjas brilhantes, com conjunto composto por blusa cropped de manga longa e saia, detalhes de franjas brilhantes na região do busto.",
    imagens: ["instagram/DcWSvx-vXnx/01.webp"],
    palavras_chave: ["Roupas Femininas", "preto", "branco", "conjunto feminino", "cropped", "saia preta", "franjas brilhantes", "estilo country"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcwszbomw_4",
    titulo: "Conjunto de vestuário feminino com franjas",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de vestuário feminino, em tons de marrom e dourado.",
    descricao_comercial: "A imagem apresenta conjunto de vestuário feminino, com conjunto de duas peças na cor marrom, aplicação de franjas brilhantes na região do busto e na barra da saia.",
    imagens: ["instagram/DcWSzBoMw-4/01.webp"],
    palavras_chave: ["Moda Feminina", "marrom", "dourado", "conjunto feminino", "moda", "roupa marrom", "franjas brilhantes"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcwtfxirbrk",
    titulo: "Conjunto de Camisa e Short Jeans",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de vestuário feminino, em tons de branco, azul e marrom.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de vestuário feminino por diferentes enquadramentos, com camisa de mangas curtas com botões frontais e gola, shorts jeans de lavagem azul com detalhes de franjas brilhantes.",
    imagens: ["instagram/DcWTfXiRBrK/01.webp", "instagram/DcWTo6Jp4cX/01.webp"],
    palavras_chave: ["Roupas Femininas", "branco", "azul", "marrom", "moda feminina", "casual", "camisa cropped", "shorts jeans"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dcwtkmsn1to",
    titulo: "Camisa preta de manga curta com botões",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Camisa preta de manga curta com botões, em tons de preto e azul.",
    descricao_comercial: "A imagem apresenta camisa preta de manga curta com botões, com camisa de cor preta, mangas curtas, gola aberta e botões frontais visíveis.",
    imagens: ["instagram/DcWTkmsN1To/01.webp"],
    palavras_chave: ["Roupas Femininas", "Preto", "Azul", "camisa preta", "moda feminina", "manga curta", "casual"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dcwy2surwqd",
    titulo: "Vestido Midi Estampado Laranja",
    categoria: "Vestidos",
    ambiente: "Estúdio fotográfico",
    descricao_curta: "Vestido Midi Estampado, para estúdio fotográfico, em tons de laranja, branco e cinza.",
    descricao_comercial: "O conjunto de 3 imagens apresenta vestido midi estampado por diferentes enquadramentos, com alças com babados, comprimento midi, decote em v e estampa em tons claros sobre fundo laranja.",
    imagens: ["instagram/DcWY2suRWQD/01.webp", "instagram/DcWYg63Or3g/01.webp", "instagram/DUp_DAbAJGx/01.webp"],
    palavras_chave: ["laranja", "Vestidos", "branco", "vestido", "moda feminina", "plus size", "midi", "estampado", "vestido midi"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dcwym82tcgs",
    titulo: "Vestido com estampa de onça",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido com estampa de onça, em tons de marrom, preto e bege.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido com estampa de onça por diferentes enquadramentos, com comprimento na altura dos joelhos, estampa de onça em tons de marrom e preto, detalhes de babados nas alças.",
    imagens: ["instagram/DcWYm82tCGs/01.webp", "instagram/DUp--QAgAyD/01.webp"],
    palavras_chave: ["Vestidos", "Marrom", "Preto", "Bege", "vestido", "animal print", "moda feminina", "estampa de onça"],
    confidence: 0.9,
    needs_review: true
  },
  {
    id: "projeto_dr4x2avgk9d",
    titulo: "Macacão feminino bicolor",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão feminino, em tons de branco, verde e preto.",
    descricao_comercial: "A imagem apresenta macacão feminino, com macacão com alças, detalhes em cor contrastante na gola e bolsos, disponível em duas opções de cores nas imagens: branco e verde.",
    imagens: ["instagram/DR4X2avgK9D/01.webp"],
    palavras_chave: ["Roupas Femininas", "branco", "verde", "preto", "macacão", "moda feminina", "roupa", "macacão casual"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dr4xeqmal0r",
    titulo: "Vestido com estampa floral em preto e branco",
    categoria: "Vestidos",
    ambiente: "Loja de roupas",
    descricao_curta: "Vestido com estampa floral em preto e branco, para loja de roupas, em tons de preto e branco.",
    descricao_comercial: "A imagem apresenta vestido com estampa floral em preto e branco, com estampa floral de grande porte, cores preto e branco, detalhe de nó ou laço lateral e mangas curtas.",
    imagens: ["instagram/DR4XeQmAL0r/01.webp"],
    palavras_chave: ["Vestidos", "Loja de roupas", "Preto", "Branco", "vestido", "moda feminina", "estampa floral"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dr4xp4wabec",
    titulo: "Vestido estampado floral transpassado",
    categoria: "Vestidos",
    ambiente: "Loja de roupas",
    descricao_curta: "Vestido estampado, para loja de roupas, em tons de branco e preto.",
    descricao_comercial: "A imagem apresenta vestido estampado, com estampa floral de grande formato, fundo branco com desenhos pretos, amarração com nó na lateral e decote transpassado.",
    imagens: ["instagram/DR4XP4WABEc/01.webp"],
    palavras_chave: ["Vestidos", "Loja de roupas", "branco", "preto", "vestido", "estampa floral", "moda feminina", "plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dr4ymquacdf",
    titulo: "Macacão Longo com Alças",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Longo, em tons de verde, amarelo e preto.",
    descricao_comercial: "A imagem apresenta macacão longo, com alças de ombro, acabamento contrastante escuro no decote e nos bolsos e dois modelos com o mesmo design em cores distintas.",
    imagens: ["instagram/DR4YMqUACDf/01.webp"],
    palavras_chave: ["Moda Feminina", "verde", "amarelo", "preto", "macacão", "macacão longo", "roupa feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_drbsvdbjd7",
    titulo: "Espaço comercial com parede verde decorativa",
    categoria: "Ambiente Comercial",
    ambiente: "Loja física",
    descricao_curta: "Espaço comercial com parede verde decorativa, para loja física, em tons de verde, branco e rosa.",
    descricao_comercial: "A imagem apresenta espaço comercial com parede verde decorativa, com parede verde vertical decorativa, texto em relevo afixado na parede e iluminação natural e ambiente interno visível.",
    imagens: ["instagram/DRBSvDbjD7-/01.webp"],
    palavras_chave: ["Ambiente Comercial", "Loja física", "verde", "branco", "rosa", "preto", "parede verde", "decoração", "loja"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_drbtklvdnxo",
    titulo: "Macacão Feminino Azul com Cinto",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio Fotográfico",
    descricao_curta: "Macacão Feminino Azul, para estúdio fotográfico, em tons de azul, branco e dourado.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão feminino azul por diferentes enquadramentos, com decote em v, macacão de manga curta, calça de corte reto e amplo e bolsa pequena com alça de mão trançada.",
    imagens: ["instagram/DRBTkLVDNXO/01.webp", "instagram/DRBTr9KDGx0/01.webp"],
    palavras_chave: ["azul", "Estúdio Fotográfico", "branco", "dourado", "Moda Feminina", "Roupas Femininas", "macacão feminino", "moda plus size"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_drbtoi9dmno",
    titulo: "Conjunto de cropped e saia preto com botões dourados",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio fotográfico",
    descricao_curta: "Conjunto de cropped e saia preto com botões dourados, para estúdio fotográfico, em tons de preto, dourado e marrom.",
    descricao_comercial: "A imagem apresenta conjunto de cropped e saia preto com botões dourados, com conjunto composto por cropped e saia de cor preta, botões frontais circulares com brilho dourado.",
    imagens: ["instagram/DRBToI9DMno/01.webp"],
    palavras_chave: ["Roupas Femininas", "Estúdio fotográfico", "preto", "dourado", "marrom", "conjunto feminino", "cropped preto", "saia preta"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsm_2owab67",
    titulo: "Bolsa de ombro marrom com textura",
    categoria: "Bolsas",
    ambiente: "Não determinado",
    descricao_curta: "Bolsa de ombro, em tons de marrom e dourado.",
    descricao_comercial: "A imagem apresenta bolsa de ombro, com textura granulada, inscrição em alto-relevo na parte frontal, fechamento com aba frontal e alças verticais.",
    imagens: ["instagram/DSm-2OwAB67/01.webp"],
    palavras_chave: ["marrom", "Bolsas", "dourado", "bolsa", "acessório", "bolsa de ombro"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsm_4x0glni",
    titulo: "Bolsa de mão off-white",
    categoria: "Bolsas",
    ambiente: "Não determinado",
    descricao_curta: "Bolsa de mão, em tons de branco off-white e dourado.",
    descricao_comercial: "A imagem apresenta bolsa de mão, com textura com granulação visível, inscrições texturizadas em alto relevo e acabamento visual claro.",
    imagens: ["instagram/DSm-4x0gLNI/01.webp"],
    palavras_chave: ["Bolsas", "branco off-white", "dourado", "bolsa", "acessório", "bolsa de mão", "bolsa feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsm_73yaaux",
    titulo: "Bolsa de ombro bege",
    categoria: "Bolsas",
    ambiente: "Não determinado",
    descricao_curta: "Bolsa de ombro, em tons de bege e dourado.",
    descricao_comercial: "A imagem apresenta bolsa de ombro, com superfície com textura granulada, inscrição em alto relevo na parte frontal, alças verticais superiores.",
    imagens: ["instagram/DSm-73YAAUX/01.webp"],
    palavras_chave: ["Bolsas", "bege", "dourado", "bolsa", "bolsa de ombro", "acessório", "bolsa bege"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsm_ebyald4",
    titulo: "Frasco de Perfume e Caixa Asad Lattafa",
    categoria: "Perfumaria",
    ambiente: "Não determinado",
    descricao_curta: "Frasco de Perfume e Caixa Asad Lattafa, em tons de preto e dourado.",
    descricao_comercial: "A imagem apresenta frasco de perfume e caixa asad lattafa, com superfície de tom preto fosco ou acetinado, elementos gráficos e textuais em tom dourado.",
    imagens: ["instagram/DSm_EbYALd4/01.webp"],
    palavras_chave: ["Perfumaria", "preto", "dourado", "perfume", "Lattafa", "Asad", "frasco"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsm_hqlghzx",
    titulo: "Frasco de perfume com embalagem",
    categoria: "Perfumaria",
    ambiente: "Não determinado",
    descricao_curta: "Frasco de perfume com embalagem, em tons de dourado, branco e bronze.",
    descricao_comercial: "A imagem apresenta frasco de perfume com embalagem, com frasco em formato circular com borda branca, detalhes centrais em relevo com acabamento reflexivo.",
    imagens: ["instagram/DSm_HQlgHZX/01.webp"],
    palavras_chave: ["Perfumaria", "Dourado", "Branco", "Bronze", "perfume", "frasco", "embalagem decorada"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsm_jxsakhv",
    titulo: "Perfume Oud Mystery Intense",
    categoria: "Perfumaria",
    ambiente: "Não determinado",
    descricao_curta: "Perfume com embalagem e caixa decorada, em tons de preto, dourado e branco.",
    descricao_comercial: "A imagem apresenta perfume com embalagem e caixa decorada, com frasco retangular escuro com ornamentações em tom dourado.",
    imagens: ["instagram/DSm_JxSAKHV/01.webp"],
    palavras_chave: ["Perfumaria", "preto", "dourado", "branco", "perfume", "frasco", "embalagem", "oud mystery intense"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnae4baoug",
    titulo: "Conjunto blusa estampada e calça jeans",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio fotográfico",
    descricao_curta: "Conjunto blusa estampada e calça jeans, para estúdio fotográfico, em tons de laranja, azul e branco.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto blusa estampada e calça jeans por diferentes enquadramentos, com blusa com decote quadrado, barra da blusa com detalhe franzido.",
    imagens: ["instagram/DSnAe4BAOUG/01.webp", "instagram/DSnAl3OAC_V/01.webp"],
    palavras_chave: ["Roupas Femininas", "Estúdio fotográfico", "laranja", "azul", "branco", "conjunto feminino", "moda plus size"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_dsnajifacf2",
    titulo: "Conjunto de Blusa Rosa e Calça Jeans Plus Size",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Roupa Feminina Plus Size, em tons de rosa e azul escuro.",
    descricao_comercial: "A imagem apresenta conjunto de roupa feminina plus size, com blusa de alça larga na cor rosa, detalhe de laço ou nó no ombro esquerdo da blusa, calça jeans azul escuro.",
    imagens: ["instagram/DSnAjIfACf2/01.webp"],
    palavras_chave: ["Roupas Femininas", "rosa", "azul escuro", "moda plus size", "roupa feminina", "blusa rosa", "calça jeans"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnat5uacgw",
    titulo: "Conjunto de Blusa com Brilho e Calça Preta",
    categoria: "Roupas Femininas",
    ambiente: "Loja",
    descricao_curta: "Conjunto de Roupa Feminina Preto com Brilho, para loja, em tons de preto e dourado.",
    descricao_comercial: "A imagem apresenta conjunto de roupa feminina preto com brilho, com blusa preta com superfície brilhante texturizada, calça preta de corte reto.",
    imagens: ["instagram/DSnAt5UACGw/01.webp"],
    palavras_chave: ["Roupas Femininas", "Loja", "preto", "dourado", "conjunto feminino", "moda feminina", "blusa preta", "calça preta"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnawk8gdnh",
    titulo: "Conjunto de Blusa de Alças e Calça",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa de Alças e Calça, em tons de preto.",
    descricao_comercial: "A imagem apresenta conjunto de blusa de alças e calça, com blusa cropped de alças largas, superfície da blusa com acabamento brilhante texturizado, calça longa preta.",
    imagens: ["instagram/DSnAwK8gDnH/01.webp"],
    palavras_chave: ["Moda Feminina", "preto", "conjunto feminino", "moda plus size", "blusa preta", "calça preta"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnayfsgi5d",
    titulo: "Blusa regata com brilho e calça preta",
    categoria: "Roupas Femininas",
    ambiente: "Loja",
    descricao_curta: "Blusa regata com brilho e calça preta, para loja, em tons de preto e dourado.",
    descricao_comercial: "A imagem apresenta blusa regata com brilho e calça preta, com blusa com decote em v, superfície da blusa com aspecto brilhante, calça de cor preta lisa.",
    imagens: ["instagram/DSnAyFsgI5d/01.webp"],
    palavras_chave: ["Roupas Femininas", "Loja", "preto", "dourado", "moda feminina", "regata preta", "calça preta", "look plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnboptgg7c",
    titulo: "Conjunto de Camiseta e Calça Jeans Rasgada",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Roupa Feminina com Camiseta Branca e Calça Jeans, em tons de branco, azul escuro e vermelho.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de roupa feminina com camiseta branca e calça jeans por diferentes enquadramentos, com camiseta de manga curta com gola v e estampa frontal.",
    imagens: ["instagram/DSnBOptgG7C/01.webp", "instagram/DSnBTWAAI6T/01.webp"],
    palavras_chave: ["Moda Feminina", "Branco", "Azul escuro", "Vermelho", "camiseta branca", "calça jeans", "look casual", "plus size"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dsnbqxfahon",
    titulo: "Calça Jeans Feminina Plus Size com Camiseta Tigre",
    categoria: "Calças",
    ambiente: "Não determinado",
    descricao_curta: "Calça Jeans Feminina Plus Size, em tons de azul escuro e bege.",
    descricao_comercial: "A imagem apresenta calça jeans feminina plus size, com calça de modelagem longa, lavagem escura, camiseta com estampa de tigre e corte reto nas pernas.",
    imagens: ["instagram/DSnBQXFAHOn/01.webp"],
    palavras_chave: ["Calças", "azul escuro", "bege", "calça jeans", "moda feminina", "plus size", "camiseta estampada"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnd5woaktu",
    titulo: "Blusa estampada folhagem com calça preta",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Blusa estampada sem mangas com calça preta, em tons de vermelho, amarelo e preto.",
    descricao_comercial: "O conjunto de 2 imagens apresenta blusa estampada sem mangas com calça preta por diferentes enquadramentos, com estampa com padronagem de folhas, decote em v.",
    imagens: ["instagram/DSnD5wOAKtu/01.webp", "instagram/DSnEApVgFSE/01.webp"],
    palavras_chave: ["Roupas Femininas", "vermelho", "amarelo", "preto", "moda feminina", "blusa estampada", "calça preta", "look casual"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dsnd_kkafkh",
    titulo: "Conjunto de Blusa Folhagem e Calça Jeans",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Calça Jeans, em tons de laranja, branco e azul escuro.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e calça jeans, com blusa com estampa folhagem, blusa com detalhe de amarrar no decote, calça jeans de cintura alta.",
    imagens: ["instagram/DSnD_KKAFKH/01.webp"],
    palavras_chave: ["Moda Feminina", "laranja", "branco", "azul escuro", "conjunto plus size", "blusa regata", "calça jeans"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsne2cvga_i",
    titulo: "Conjunto Feminino Blusa Ciganinha e Shorts",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto Feminino Blusa e Shorts, em tons de laranja, branco e bege.",
    descricao_comercial: "A imagem apresenta conjunto feminino blusa e shorts, com estampa abstrata, blusa com decote ombro a ombro, babado na blusa e shorts de tom claro.",
    imagens: ["instagram/DSnE2cvgA_i/01.webp"],
    palavras_chave: ["Roupas Femininas", "laranja", "branco", "bege", "conjunto feminino", "moda plus size", "blusa ciganinha", "shorts"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsne4zkanro",
    titulo: "Conjunto de Blusa Ombro a Ombro e Short Jeans",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio Fotográfico",
    descricao_curta: "Conjunto de Blusa e Short Jeans, para estúdio fotográfico, em tons de branco, verde e azul.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de blusa e short jeans por diferentes enquadramentos, com blusa com decote ombro a ombro, estampa de folhagem verde sobre fundo branco, short jeans em tom azul escuro.",
    imagens: ["instagram/DSnE4ZKANRO/01.webp", "instagram/DSnEzyIgML4/01.webp"],
    palavras_chave: ["Roupas Femininas", "Estúdio Fotográfico", "branco", "verde", "azul", "moda feminina", "look casual", "short jeans"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_dsneqkzgjyo",
    titulo: "Conjunto blusa estampada floral e shorts jeans",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto blusa estampada e shorts jeans, em tons de branco, azul e vermelho.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto blusa estampada e shorts jeans por diferentes enquadramentos, com estampa colorida com temática floral e de aves na blusa, shorts com barra virada.",
    imagens: ["instagram/DSnEQkzgJYO/01.webp", "instagram/DSnEZn8gGJ0/01.webp"],
    palavras_chave: ["moda feminina", "branco", "azul", "vermelho", "verde", "blusa estampada", "shorts jeans", "plus size"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dsnetxpacxz",
    titulo: "Conjunto de Blusa Geométrica e Shorts",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio Fotográfico",
    descricao_curta: "Conjunto de Blusa e Shorts, para estúdio fotográfico, em tons de preto, azul e branco.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e shorts, com blusa com padronagem geométrica e abstrata, shorts com barra dobrada, shorts com bolsos e costuras aparentes.",
    imagens: ["instagram/DSnETxPACxz/01.webp"],
    palavras_chave: ["Roupas Femininas", "Estúdio Fotográfico", "Preto", "Azul", "Branco", "conjunto feminino", "blusa estampada", "shorts jeans"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnfieealli",
    titulo: "Conjunto feminino de blusa regata folhagens e shorts",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio fotográfico",
    descricao_curta: "Conjunto feminino de blusa regata e shorts, para estúdio fotográfico, em tons de verde, bege e branco.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto feminino de blusa regata e shorts por diferentes enquadramentos, com blusa regata com alças, estampa com motivos de folhagens, shorts com bolsos frontais.",
    imagens: ["instagram/DSnFIEeALLi/01.webp", "instagram/DSnFLU3ADOQ/01.webp"],
    palavras_chave: ["Roupas Femininas", "verde", "bege", "moda feminina", "shorts", "casual", "conjunto", "blusa regata", "plus size"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_dsnfiflglht",
    titulo: "Conjunto de Blusa Branca e Bermuda Vermelha",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio Fotográfico",
    descricao_curta: "Conjunto de Roupa Feminina Plus Size, para estúdio fotográfico, em tons de branco, vermelho e bege.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de roupa feminina plus size por diferentes enquadramentos, com blusa branca com decote ombro a ombro, bermuda vermelha com botões frontais visíveis.",
    imagens: ["instagram/DSnFiFlgLHT/01.webp", "instagram/DSnFmyRAFoj/01.webp"],
    palavras_chave: ["Roupas Femininas", "Estúdio Fotográfico", "branco", "vermelho", "bege", "moda feminina", "plus size", "blusa branca", "bermuda vermelha"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dsnfj3cgfbn",
    titulo: "Conjunto de Blusa com Laço no Ombro e Shorts",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Shorts, em tons de branco, azul e bege.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e shorts, com blusa de alça com laço decorativo em um dos ombros, shorts jeans com barra desfiada.",
    imagens: ["instagram/DSnFJ3CgFBN/01.webp"],
    palavras_chave: ["Moda Feminina", "branco", "azul", "bege", "blusa branca", "shorts jeans", "look casual", "plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnfkpqgjwt",
    titulo: "Conjunto Feminino com Blusa Sem Mangas e Bermuda",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto Feminino com Blusa Sem Mangas e Bermuda, em tons de vermelho, bege e branco.",
    descricao_comercial: "A imagem apresenta conjunto feminino com blusa sem mangas e bermuda, com blusa com alças largas e detalhe de botões na gola e bermuda de comprimento acima dos joelhos.",
    imagens: ["instagram/DSnFkpQgJWT/01.webp"],
    palavras_chave: ["Moda Feminina", "Vermelho", "Bege", "Branco", "conjunto feminino", "blusa vermelha", "bermuda", "moda plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsng20baevc",
    titulo: "Macacão estampado mostarda",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão estampado, em tons de mostarda, marrom e bege.",
    descricao_comercial: "A imagem apresenta macacão estampado, com peça única, estampa floral contínua em tons contrastantes, corte reto nas pernas da calça e acabamento franzido na gola.",
    imagens: ["instagram/DSnG20BAEvC/01.webp"],
    palavras_chave: ["Roupas Femininas", "Mostarda", "Marrom", "Bege", "macacão", "feminino", "moda", "estampa floral", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsngjz4aldh",
    titulo: "Macacão Longo Estampado Floral",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Longo Estampado, em tons de marrom, mostarda e bege.",
    descricao_comercial: "A imagem apresenta macacão longo estampado, com estampa com padronagem floral em linhas claras, corte sem mangas com decote arredondado, calça de pernas largas.",
    imagens: ["instagram/DSnGjz4ALDh/01.webp"],
    palavras_chave: ["Roupas Femininas", "marrom", "mostarda", "bege", "macacão", "moda feminina", "estampado", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsngzv6ap2p",
    titulo: "Macacão Longo Estampado Floral Laranja",
    categoria: "Roupas Femininas",
    ambiente: "Área Externa",
    descricao_curta: "Macacão Longo Estampado, para área externa, em tons de laranja, marrom e verde.",
    descricao_comercial: "A imagem apresenta macacão longo estampado, com estampa com padronagem floral abstrata, calça de pernas compridas e amplas, cinto texturizado na cintura.",
    imagens: ["instagram/DSnGzV6AP2p/01.webp"],
    palavras_chave: ["Roupas Femininas", "Área Externa", "laranja", "marrom", "verde", "macacão", "macacão longo", "moda feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnhactabyp",
    titulo: "Conjunto de Blusa Bicolor e Calça",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Calça, em tons de marrom e off-white.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e calça, com blusa com recortes bicolores nos ombros, calça com bolsos frontais aparentes, cós com detalhe de listras.",
    imagens: ["instagram/DSnHacTABYP/01.webp"],
    palavras_chave: ["Roupas Femininas", "Marrom", "Off-white", "conjunto feminino", "blusa", "calça", "moda feminina", "bicolor"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnhcqtghhs",
    titulo: "Looks Femininos com Estampa Floral e Cores Neutras",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Looks Femininos com Estampa Floral e Cores Neutras, em tons de branco, marrom e bege.",
    descricao_comercial: "A imagem apresenta looks femininos com estampa floral e cores neutras, com estampa floral estilizada, detalhe de renda nas mangas, fundo branco com elementos marrons.",
    imagens: ["instagram/DSnHcqTgHHS/01.webp"],
    palavras_chave: ["Roupas Femininas", "branco", "marrom", "bege", "moda feminina", "look casual", "estampa floral", "roupas plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnhyjwgnpp",
    titulo: "Conjunto de Vestuário Feminino Floral",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Vestuário Feminino, em tons de branco e marrom.",
    descricao_comercial: "A imagem apresenta conjunto de vestuário feminino, com estampa com padrão de flores estilizadas, blusa de manga curta, calça lisa e saia longa.",
    imagens: ["instagram/DSnHYJwgNPp/01.webp"],
    palavras_chave: ["Moda Feminina", "branco", "marrom", "roupa feminina", "estampa floral", "conjunto feminino", "saia longa", "calça"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsni4elge0c",
    titulo: "Conjunto de Blusa e Shorts Verde Claro",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Shorts, em tons de verde claro.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e shorts, com conjunto de duas peças na cor verde claro, blusa com alças largas e detalhe de nó na parte frontal, shorts com bolsos laterais.",
    imagens: ["instagram/DSnI4eLgE0c/01.webp"],
    palavras_chave: ["Verde claro", "Moda Feminina", "conjunto feminino", "moda plus size", "blusa", "shorts"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsni7aigdhg",
    titulo: "Conjunto de Blusa com Nó e Shorts Azul Petróleo",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Shorts, em tons de azul petróleo.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de blusa e shorts por diferentes enquadramentos, com conjunto de duas peças na mesma cor, blusa com decote em v, detalhe de abertura e nó na parte frontal.",
    imagens: ["instagram/DSnI7aIgDhg/01.webp", "instagram/DSnIt8ggK6M/01.webp"],
    palavras_chave: ["Azul Petróleo", "Moda Feminina", "conjunto feminino", "moda plus size", "blusa com nó", "shorts"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dsnibxcgdls",
    titulo: "Conjunto Fitness Magenta com Top e Legging",
    categoria: "Moda Fitness",
    ambiente: "Academia",
    descricao_curta: "Conjunto de Roupa Fitness, para academia, em tons de magenta, vinho e rosa escuro.",
    descricao_comercial: "O conjunto de 3 imagens apresenta conjunto de roupa fitness por diferentes enquadramentos, com legging de cintura alta, acabamento liso, conjunto composto por top e legging de mesma cor.",
    imagens: ["instagram/DSnIBxcgDls/01.webp", "instagram/DSnIDHmgOFR/01.webp", "instagram/DSnIEqygC3E/01.webp"],
    palavras_chave: ["Moda Fitness", "Academia", "magenta", "conjunto fitness", "legging", "roupa feminina", "vinho", "top esportivo"],
    confidence: 0.79,
    needs_review: false
  },
  {
    id: "projeto_dsniegbagww",
    titulo: "Conjunto Fitness Feminino Plus Size Preto",
    categoria: "Moda Fitness",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto Fitness Feminino Plus Size, em tons de preto.",
    descricao_comercial: "O conjunto de 3 imagens apresenta conjunto fitness feminino plus size por diferentes enquadramentos, com calça legging de cintura alta, conjunto de duas peças, cor preta sólida e top de alças largas.",
    imagens: ["instagram/DSnIeGBAGWW/01.webp", "instagram/DSnIUCSAFzl/01.webp", "instagram/DSnIW9RABtP/01.webp"],
    palavras_chave: ["Preto", "Moda Fitness", "moda plus size", "roupa feminina", "conjunto fitness", "legging preta", "top esportivo"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dsnj1yygmpx",
    titulo: "Vestido verde com decote quadrado",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido verde com decote quadrado, em tons de verde, dourado e vermelho.",
    descricao_comercial: "A imagem apresenta vestido verde com decote quadrado, com vestido verde de mangas curtas, decote quadrado, aberturas laterais na cintura e detalhes decorativos dourados.",
    imagens: ["instagram/DSnJ1YygMpX/01.webp"],
    palavras_chave: ["Vestidos", "verde", "dourado", "vermelho", "vestido", "vestido verde", "moda feminina", "roupa feminina", "decote quadrado"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnj4npak7y",
    titulo: "Vestido vermelho com decote quadrado",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido vermelho com decote quadrado, em tons de vermelho e branco.",
    descricao_comercial: "A imagem apresenta vestido vermelho com decote quadrado, com vestido de cor vermelha, decote quadrado, mangas curtas levemente amplas e comprimento abaixo do joelho.",
    imagens: ["instagram/DSnJ4NpAK7y/01.webp"],
    palavras_chave: ["Vestidos", "vermelho", "branco", "vestido", "vestido vermelho", "moda feminina", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnjbqoaixv",
    titulo: "Conjunto feminino sem mangas com shorts rosa",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto feminino sem mangas com shorts, em tons de rosa claro e branco.",
    descricao_comercial: "A imagem apresenta conjunto feminino sem mangas com shorts, com vestuário de duas peças na cor rosa claro, blusa com detalhe franzido na parte superior, shorts de comprimento curto.",
    imagens: ["instagram/DSnJbQoAIXV/01.webp"],
    palavras_chave: ["rosa claro", "Moda Feminina", "branco", "conjunto feminino", "moda plus size", "blusa e shorts", "casual"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnjchegj10",
    titulo: "Conjunto de cropped e shorts coral",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio",
    descricao_curta: "Conjunto de cropped e shorts, para estúdio, em tons de branco, coral e rosa claro.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de cropped e shorts por diferentes enquadramentos, com conjunto monocromático em tom coral, cropped de alças largas com decote quadrado, shorts com botões frontais.",
    imagens: ["instagram/DSnJchEgJ10/01.webp", "instagram/DSnJZ0bgFcd/01.webp"],
    palavras_chave: ["Roupas Femininas", "branco", "cropped", "shorts", "coral", "conjunto", "moda feminina", "plus size", "casual"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dsnjhjigh8z",
    titulo: "Conjunto feminino de regata e shorts bege",
    categoria: "Roupas Femininas",
    ambiente: "Estúdio Fotográfico",
    descricao_curta: "Conjunto feminino de regata e shorts, para estúdio fotográfico, em tons de branco e bege.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto feminino de regata e shorts por diferentes enquadramentos, com regata de alças finas, decote em v, shorts com bolsos laterais visíveis.",
    imagens: ["instagram/DSnJHJigH8Z/01.webp", "instagram/DSnJJojANFc/01.webp"],
    palavras_chave: ["branco", "bege", "conjunto", "regata", "shorts", "moda feminina", "plus size", "Roupas Femininas"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_dsnjiadghhw",
    titulo: "Conjunto de Blusa e Shorts com Cordão",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Shorts, em tons de bege e branco.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e shorts, com conjunto composto por duas peças de mesma cor, blusa sem mangas com alças largas, shorts com elástico e cordão ajustável.",
    imagens: ["instagram/DSnJIaDgHHw/01.webp"],
    palavras_chave: ["Moda Feminina", "bege", "branco", "conjunto feminino", "moda plus size", "blusa e shorts", "casual"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnjtyaamzi",
    titulo: "Conjunto de cropped e shorts preto com faixa",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de cropped e shorts, em tons de preto.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de cropped e shorts por diferentes enquadramentos, com conjunto de duas peças na cor preta, cropped de alças largas com decote quadrado, shorts com passantes e faixa.",
    imagens: ["instagram/DSnJTYaAMzi/01.webp", "instagram/DSnJV85gOH-/01.webp"],
    palavras_chave: ["Moda Feminina", "preto", "conjunto feminino", "cropped", "shorts", "moda plus size", "roupa preta"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_dsnju2vadyu",
    titulo: "Conjunto de Roupa Feminina Preto com Acessório",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Roupa Feminina Preto, em tons de preto.",
    descricao_comercial: "A imagem apresenta conjunto de roupa feminina preto, com conjunto composto por blusa e parte inferior pretas, blusa com alças largas e decote quadrado, bolsa pequena de mão.",
    imagens: ["instagram/DSnJU2vADyU/01.webp"],
    palavras_chave: ["Roupas Femininas", "Preto", "roupa feminina", "conjunto preto", "moda plus size", "blusa preta"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnjzzugnhf",
    titulo: "Vestido curto vermelho manga solta",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido curto vermelho, em tons de vermelho.",
    descricao_comercial: "A imagem apresenta vestido curto vermelho, com vestido de cor vermelha, decote quadrado, mangas curtas com caimento solto e comprimento curto.",
    imagens: ["instagram/DSnJzZUgNhF/01.webp"],
    palavras_chave: ["Vestidos", "Vermelho", "vestido", "vestido curto", "vestido vermelho", "moda feminina", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnkb0lgpce",
    titulo: "Macaquinho vermelho de lantejoulas",
    categoria: "Roupas Femininas",
    ambiente: "Loja física",
    descricao_curta: "Macaquinho vermelho de lantejoulas, para loja física, em tons de vermelho, marrom e dourado.",
    descricao_comercial: "A imagem apresenta macaquinho vermelho de lantejoulas, com superfície revestida de lantejoulas vermelhas, mangas curtas, decote ombro a ombro.",
    imagens: ["instagram/DSnKb0lgPce/01.webp"],
    palavras_chave: ["Vermelho", "Roupas Femininas", "Loja física", "Marrom", "Dourado", "macaquinho", "lantejoulas", "moda feminina", "festa"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnkinkgojb",
    titulo: "Vestido curto azul com fenda",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido curto azul, em tons de azul e branco.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido curto azul por diferentes enquadramentos, com vestido de cor azul, mangas curtas com volume, decote em v e detalhe de fenda frontal na saia.",
    imagens: ["instagram/DSnKInKgOjb/01.webp", "instagram/DSnKM1XgNHe/01.webp"],
    palavras_chave: ["Vestidos", "azul", "branco", "vestido", "vestido curto", "moda feminina", "vestido com fenda", "vestido azul"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dsnkk0cajq9",
    titulo: "Vestido curto amarelo decote V",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido curto amarelo, em tons de amarelo e branco.",
    descricao_comercial: "A imagem apresenta vestido curto amarelo, com vestido de cor amarela, decote em v, mangas curtas com franzido e detalhe de fenda frontal na saia.",
    imagens: ["instagram/DSnKK0cAJq9/01.webp"],
    palavras_chave: ["amarelo", "Vestidos", "branco", "vestido", "moda feminina", "vestido curto", "decote V"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnkvhmaard",
    titulo: "Macaquinho branco com brilho",
    categoria: "Moda Feminina",
    ambiente: "Loja de Roupas",
    descricao_curta: "Macaquinho branco com brilho, para loja de roupas, em tons de branco, marrom e preto.",
    descricao_comercial: "A imagem apresenta macaquinho branco com brilho, com macaquinho branco com decote ombro a ombro, superfície com brilho, mangas curtas e calçado marrom de salto.",
    imagens: ["instagram/DSnKVhmAArd/01.webp"],
    palavras_chave: ["Moda Feminina", "branco", "Loja de Roupas", "marrom", "preto", "macaquinho", "brilho"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnkzh7ah7z",
    titulo: "Macacão com aplicação de paetês pretos",
    categoria: "Roupas Femininas",
    ambiente: "Loja física",
    descricao_curta: "Macacão com aplicação de paetês pretos, para loja física, em tons de preto e prata.",
    descricao_comercial: "A imagem apresenta macacão com aplicação de paetês pretos, com mangas volumosas e cintura marcada.",
    imagens: ["instagram/DSnKZh7AH7Z/01.webp"],
    palavras_chave: ["Roupas Femininas", "Loja física", "preto", "prata", "macacão", "paetê", "moda feminina", "festa"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnlexzglbv",
    titulo: "Macacão preto pernas largas",
    categoria: "Moda Feminina",
    ambiente: "Loja física",
    descricao_curta: "Macacão preto, para loja física, em tons de preto, vermelho e rosa.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão preto por diferentes enquadramentos, com vestuário feminino preto de alças, decote em v, calça de pernas largas e enfeites natalinos ao fundo.",
    imagens: ["instagram/DSnLeXZgLBv/01.webp", "instagram/DSnLRQsAJuT/01.webp"],
    palavras_chave: ["Moda Feminina", "preto", "vermelho", "rosa", "branco", "macacão", "loja", "Loja física", "moda"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dsnljfmglxk",
    titulo: "Macacão longo com alças finas",
    categoria: "Moda Feminina",
    ambiente: "Sala de estar",
    descricao_curta: "Macacão longo, para sala de estar, em tons de azul, dourado e cinza.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão longo por diferentes enquadramentos, com alças finas, bolsa com acabamento brilhante, peça única e decote em v.",
    imagens: ["instagram/DSnLJfMgLXK/01.webp", "instagram/DSnLNTxAJYz/01.webp"],
    palavras_chave: ["Moda Feminina", "Sala de estar", "azul", "dourado", "macacão", "macacão longo", "plus size", "roupa casual"],
    confidence: 0.9,
    needs_review: true
  },
  {
    id: "projeto_dsnlmuwafbs",
    titulo: "Macacão longo busto franzido",
    categoria: "Moda Feminina",
    ambiente: "Sala de estar",
    descricao_curta: "Macacão longo, para sala de estar, em tons de azul.",
    descricao_comercial: "A imagem apresenta macacão longo, com aparência visual texturizada, modelagem longa, decote com alças finas e região do busto com costuras franzidas elásticas.",
    imagens: ["instagram/DSnLMUWAFBs/01.webp"],
    palavras_chave: ["Moda Feminina", "Sala de estar", "azul", "macacão", "macacão longo", "roupa feminina"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnlt_kajib",
    titulo: "Macacão preto de alça larga textura vertical",
    categoria: "Moda Feminina",
    ambiente: "Loja de Roupas",
    descricao_curta: "Macacão preto de alça larga com textura listrada vertical, para loja de roupas, em tons de preto, rosa e prata.",
    descricao_comercial: "A imagem apresenta macacão preto de alça larga com textura listrada vertical, com vestuário feminino de cor preta, presença de árvore de natal decorada em tom de rosa.",
    imagens: ["instagram/DSnLT_KAJiB/01.webp"],
    palavras_chave: ["Moda Feminina", "Loja de Roupas", "preto", "rosa", "prata", "branco", "macacão preto", "loja"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnmk_fahut",
    titulo: "Macacão longo feminino cintura marcada",
    categoria: "Moda Feminina",
    ambiente: "Área externa",
    descricao_curta: "Macacão longo feminino, para área externa, em tons de azul, verde e bege.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão longo feminino por diferentes enquadramentos, com peça única, decote em v, mangas curtas e cintura marcada com franzido elástico.",
    imagens: ["instagram/DSnMK_FAHUt/01.webp", "instagram/DSnMOfIAEC0/01.webp"],
    palavras_chave: ["Moda Feminina", "azul", "macacão", "plus size", "Área externa", "verde", "bege", "casual"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dsnmmy2ah0f",
    titulo: "Macaquinho Longo Azul-marinho",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macaquinho Longo, em tons de azul-marinho.",
    descricao_comercial: "A imagem apresenta macaquinho longo, com decote em v, mangas curtas, cintura marcada com elástico ou franzido e modelagem longa nas pernas.",
    imagens: ["instagram/DSnMMy2AH0F/01.webp"],
    palavras_chave: ["Roupas Femininas", "Azul-marinho", "macaquinho", "moda feminina", "roupa azul-marinho", "decote V"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnmt65geqw",
    titulo: "Macacão azul com cinto",
    categoria: "Moda Feminina",
    ambiente: "Estúdio Fotográfico",
    descricao_curta: "Macacão azul com cinto, para estúdio fotográfico, em tons de azul, branco e dourado.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão azul com cinto por diferentes enquadramentos, com macacão de cor azul claro, mangas curtas amplas, calça de corte reto e decote em v cruzado.",
    imagens: ["instagram/DSnMT65gEqw/01.webp", "instagram/DSnMXSLALkC/01.webp"],
    palavras_chave: ["Moda Feminina", "azul", "branco", "dourado", "macacão", "cinto", "macacão azul", "look casual", "plus size"],
    confidence: 0.9,
    needs_review: true
  },
  {
    id: "projeto_dsnmv0kgmi6",
    titulo: "Macacão com Cinto e Decote V Marrom",
    categoria: "Moda Feminina",
    ambiente: "Externo",
    descricao_curta: "Macacão com Cinto e Decote V, para externo, em tons de marrom, bege e azul.",
    descricao_comercial: "A imagem apresenta macacão com cinto e decote v, com macacão longo, decote v transpassado, mangas curtas amplas e calça de corte reto com costura frontal central.",
    imagens: ["instagram/DSnMV0KgMi6/01.webp"],
    palavras_chave: ["Moda Feminina", "Externo", "marrom", "bege", "azul", "macacão", "plus size", "decote V", "cinto"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dsnpgaqajt7",
    titulo: "Conjunto de lingerie marrom com alças finas",
    categoria: "Moda Íntima",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de lingerie marrom, em tons de marrom e dourado.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de lingerie marrom por diferentes enquadramentos, com conjunto de duas peças na cor marrom, top com alças finas reguláveis, calcinha de corte alto.",
    imagens: ["instagram/DSnPgaqAJt7/01.webp", "instagram/DSnPkWcAEAy/01.webp"],
    palavras_chave: ["Moda Íntima", "marrom", "dourado", "conjunto feminino", "top marrom", "calcinha alta", "lingerie"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dsnph_uaou2",
    titulo: "Conjunto de lingerie de duas peças",
    categoria: "Moda Íntima",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de lingerie de duas peças, em tons de marrom e bege.",
    descricao_comercial: "A imagem apresenta conjunto de lingerie de duas peças, com conjunto em tom marrom escuro, top com alças finas e decote em v e calcinha de cós alto.",
    imagens: ["instagram/DSnPh_uAOU2/01.webp"],
    palavras_chave: ["marrom", "Moda Íntima", "bege", "conjunto", "lingerie", "top", "calcinha", "moda feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dsnpoqbgaeb",
    titulo: "Conjunto de lingerie e short doll preto com renda",
    categoria: "Moda Íntima",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de lingerie e short doll, em tons de preto.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de lingerie e short doll por diferentes enquadramentos, com alças finas, peça de cor preta, decote em v com acabamento em renda.",
    imagens: ["instagram/DSnPoqbgAeb/01.webp", "instagram/DSnQMPCgO5R/01.webp"],
    palavras_chave: ["Moda Íntima", "preto", "conjunto", "lingerie", "short doll", "renda", "plus size"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dsnppq3aep7",
    titulo: "Conjunto de lingerie e short com renda vinho",
    categoria: "Moda Íntima",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de lingerie e short, em tons de vinho.",
    descricao_comercial: "A imagem apresenta conjunto de lingerie e short, com conjunto composto por blusa e short, aplicação de renda na região superior da blusa, aplicação de renda na barra.",
    imagens: ["instagram/DSnPpq3AEp7/01.webp"],
    palavras_chave: ["Moda Íntima", "vinho", "conjunto", "lingerie", "short", "renda"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dt55knsis9t",
    titulo: "Vestido Longo Estampado Pássaros e Flores",
    categoria: "Vestidos",
    ambiente: "Loja de Roupas",
    descricao_curta: "Vestido Longo Estampado, para loja de roupas, em tons de azul, verde e amarelo.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido longo estampado por diferentes enquadramentos, com decote em v, vestido longo com estampa colorida de pássaro e flores, mangas curtas amplas.",
    imagens: ["instagram/DT55KnSiS9T/01.webp", "instagram/DT548VaCYyu/01.webp"],
    palavras_chave: ["Loja de Roupas", "Vestidos", "azul", "verde", "amarelo", "rosa", "vestido longo", "moda feminina"],
    confidence: 0.79,
    needs_review: false
  },
  {
    id: "projeto_dup_1c5gjx",
    titulo: "Vestido longo decote quadrado rosa",
    categoria: "Vestidos",
    ambiente: "Área externa",
    descricao_curta: "Vestido longo, para área externa, em tons de rosa, magenta e verde.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido longo por diferentes enquadramentos, com mangas curtas, decote quadrado, vestido longo na cor rosa e fenda frontal na saia.",
    imagens: ["instagram/DUp_1c5gJx-/01.webp", "instagram/DUp_7LwgGvr/01.webp"],
    palavras_chave: ["Vestidos", "Área externa", "rosa", "magenta", "vestido longo", "vestido rosa", "moda feminina", "fenda frontal"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dup_4uwgd61",
    titulo: "Vestido longo camadas laranja com fenda",
    categoria: "Vestidos",
    ambiente: "Loja de roupas",
    descricao_curta: "Vestido longo, para loja de roupas, em tons de laranja, verde e rosa.",
    descricao_comercial: "A imagem apresenta vestido longo, com vestido longo de cor laranja com mangas curtas franzidas, saia longa com camadas e fenda frontal.",
    imagens: ["instagram/DUp_4uWgD61/01.webp"],
    palavras_chave: ["Loja de roupas", "Vestidos", "laranja", "verde", "rosa", "vestido longo", "moda feminina", "roupa plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dup_bn7aivt",
    titulo: "Macacão Rosa Plus Size Babados",
    categoria: "Roupas Femininas",
    ambiente: "Externo",
    descricao_curta: "Macacão Rosa Plus Size, para externo, em tons de rosa, branco e marrom.",
    descricao_comercial: "A imagem apresenta macacão rosa plus size, com macacão de cor rosa, mangas curtas com babados, detalhe franzido na região superior traseira e calça de pernas longas e retas.",
    imagens: ["instagram/DUp_bN7AIVT/01.webp"],
    palavras_chave: ["Roupas Femininas", "Externo", "rosa", "branco", "marrom", "verde", "macacão", "moda feminina", "plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dup_ehhaagz",
    titulo: "Conjunto feminino rosa com blusa e calça",
    categoria: "Roupas Femininas",
    ambiente: "Ambiente externo",
    descricao_curta: "Conjunto feminino rosa com blusa e calça, para ambiente externo, em tons de rosa, branco e marrom.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto feminino rosa com blusa e calça por diferentes enquadramentos, com conjunto de duas peças na cor rosa, blusa de mangas curtas com decote quadrado, calça comprida.",
    imagens: ["instagram/DUp_eHHAAgz/01.webp", "instagram/DUp_Xj_AIZZ/01.webp"],
    palavras_chave: ["rosa", "branco", "marrom", "conjunto feminino", "moda plus size", "blusa rosa", "calça rosa", "Roupas Femininas"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dup_gd0ahdy",
    titulo: "Vestido com estampa animal print em camadas",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido com estampa animal print, em tons de marrom, preto e bege.",
    descricao_comercial: "A imagem apresenta vestido com estampa animal print, com estampa com padrão animal print, alças com babados, detalhe franzido na região do tronco e saia com recortes em camadas.",
    imagens: ["instagram/DUp_GD0AHdy/01.webp"],
    palavras_chave: ["Vestidos", "marrom", "preto", "bege", "branco", "vestido", "animal print", "moda feminina", "plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dup_h1egmhz",
    titulo: "Macaquinho rosa com amarração na cintura",
    categoria: "Roupas Femininas",
    ambiente: "Área externa com jardim",
    descricao_curta: "Macaquinho rosa, para área externa com jardim, em tons de rosa, marrom e verde.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macaquinho rosa por diferentes enquadramentos, com peça única curta, decote em v, alças e amarração na cintura.",
    imagens: ["instagram/DUp_h1EgMHZ/01.webp", "instagram/DUp_pUFABTE/01.webp"],
    palavras_chave: ["Roupas Femininas", "Área externa com jardim", "rosa", "marrom", "macaquinho", "moda feminina", "plus size"],
    confidence: 0.9,
    needs_review: false
  },
  {
    id: "projeto_dup_leuafyp",
    titulo: "Macacão Curto Rosa Claro Franzido",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Curto Rosa, em tons de rosa, verde e marrom.",
    descricao_comercial: "A imagem apresenta macacão curto rosa, com peça única curta, cor rosa claro e detalhe franzido nas costas.",
    imagens: ["instagram/DUp_leUAFyp/01.webp"],
    palavras_chave: ["rosa", "Roupas Femininas", "verde", "marrom", "macacão", "macacão curto", "moda feminina", "roupa plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dup_lhqghym",
    titulo: "Conjunto de Roupa Feminina Preto Alças Largas",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Roupa Feminina Preto, em tons de preto.",
    descricao_comercial: "O conjunto de 2 imagens apresenta conjunto de roupa feminina preto por diferentes enquadramentos, com conjunto composto por blusa e short de cor preta, blusa de alças largas e decote quadrado.",
    imagens: ["instagram/DUp_LHqgHym/01.webp", "instagram/DUp_RQpgH5M/01.webp"],
    palavras_chave: ["Roupas Femininas", "preto", "look casual", "moda feminina", "conjunto preto", "regata preta", "short preto"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_dup_ousgipv",
    titulo: "Conjunto feminino preto de cropped e shorts cintura alta",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto feminino preto de cropped e shorts, em tons de preto e bege claro.",
    descricao_comercial: "A imagem apresenta conjunto feminino preto de cropped e shorts, com conjunto monocromático na cor preta, cropped de alças largas, shorts de cintura alta e acessórios metálicos.",
    imagens: ["instagram/DUp_OUsgIPV/01.webp"],
    palavras_chave: ["Moda Feminina", "preto", "bege claro", "conjunto feminino", "cropped", "shorts", "look preto"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dup_tdqak1f",
    titulo: "Macacão longo verde com cinto largo",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Macacão longo feminino, em tons de verde, marrom e bege.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão longo feminino por diferentes enquadramentos, com macacão longo de alças finas, decote em v, corte fluido nas pernas e cinto marrom largo com fivela grande.",
    imagens: ["instagram/DUp_tDqAK1F/01.webp", "instagram/DUp_yICgJSf/01.webp"],
    palavras_chave: ["Moda Feminina", "verde", "marrom", "bege", "macacão", "macacão longo", "plus size", "look casual", "macacão verde"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dup_vbyaprw",
    titulo: "Macacão Longo Preto Fluido",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Longo Preto, em tons de preto e branco.",
    descricao_comercial: "A imagem apresenta macacão longo preto, com peça única na cor preta, parte superior com alças e decote em v, parte inferior com pernas largas e fluídas e corte plus size.",
    imagens: ["instagram/DUp_vbYAPRw/01.webp"],
    palavras_chave: ["Preto", "Roupas Femininas", "Branco", "macacão", "macacão longo", "moda feminina", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_duqa1kpah5g",
    titulo: "Macacão Feminino Plus Size Marrom Decote V",
    categoria: "Roupas Femininas",
    ambiente: "Externo",
    descricao_curta: "Macacão Feminino Plus Size, para externo, em tons de marrom, branco e azul.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão feminino plus size por diferentes enquadramentos, com decote em v, mangas curtas e amplas, macacão longo de cor marrom e calça de corte reto.",
    imagens: ["instagram/DUqA1kPAH5G/01.webp", "instagram/DUqAwGIAHrb/01.webp"],
    palavras_chave: ["moda feminina", "Externo", "marrom", "branco", "azul", "macacão", "plus size", "macacão longo", "Roupas Femininas"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_duqabj_gdda",
    titulo: "Conjunto de Blusa e Calça Ampla Bege",
    categoria: "Moda Feminina",
    ambiente: "Externo",
    descricao_curta: "Conjunto de Blusa e Calça, para externo, em tons de bege e laranja.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e calça, com vestuário em tom claro, blusa com decote quadrado, calça de pernas largas e cenário externo com paredes alaranjadas.",
    imagens: ["instagram/DUqAbj_gDda/01.webp"],
    palavras_chave: ["Moda Feminina", "Externo", "bege", "laranja", "conjunto feminino", "moda plus size", "blusa e calça"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_duqacsjamzo",
    titulo: "Vestido Midi Vinho com Fenda Lateral",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido Midi Feminino, em tons de dourado, bege e vinho.",
    descricao_comercial: "O conjunto de 4 imagens apresenta vestido midi feminino por diferentes enquadramentos, com fenda lateral na saia, bolsa com acabamento brilhante, vestido longo de alças finas e decote quadrado.",
    imagens: ["instagram/DUqACSJAMZo/01.webp", "instagram/DUqAIUMALxv/01.webp", "instagram/DUqAKnXgAAd/01.webp", "instagram/DUqCcMwgIPk/01.webp"],
    palavras_chave: ["Vestidos", "dourado", "bege", "moda feminina", "vinho", "vestido", "vestido longo", "plus size", "fenda lateral", "vestido midi"],
    confidence: 0.95,
    needs_review: false
  },
  {
    id: "projeto_duqakvwaawx",
    titulo: "Macacão com Cinto e Mangas Amplas Bege",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Macacão com Cinto, em tons de bege e marrom.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão com cinto por diferentes enquadramentos, com macacão longo, decote em v, mangas amplas e calças compridas de corte reto.",
    imagens: ["instagram/DUqAkVWAAWX/01.webp", "instagram/DUqAYs5gOXf/01.webp"],
    palavras_chave: ["Moda Feminina", "bege", "marrom", "macacão", "plus size", "cinto", "roupa feminina", "macacão longo"],
    confidence: 1.0,
    needs_review: true
  },
  {
    id: "projeto_duqaynggjpm",
    titulo: "Macacão Longo Verde-Escuro com Fivela",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Longo, em tons de verde-escuro.",
    descricao_comercial: "A imagem apresenta macacão longo, com cor verde-escuro, decote em v, mangas curtas amplas e cinto integrado com fivela na cintura.",
    imagens: ["instagram/DUqAynGgJPm/01.webp"],
    palavras_chave: ["Verde-escuro", "Roupas Femininas", "macacão", "macacão longo", "moda feminina", "roupa feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_duqb5nzab3j",
    titulo: "Conjunto floral estampado espelho",
    categoria: "Moda Feminina",
    ambiente: "Loja de Roupas",
    descricao_curta: "Conjunto de vestuário feminino estampado refletido no espelho, para loja de roupas, em tons de preto, branco e verde.",
    descricao_comercial: "A imagem apresenta conjunto de vestuário feminino estampado refletido no espelho, com estampa floral em tons de branco sobre fundo preto, moldura de espelho decorada.",
    imagens: ["instagram/DUqB5nZAB3J/01.webp"],
    palavras_chave: ["Loja de Roupas", "Moda Feminina", "preto", "branco", "verde", "rosa", "moda", "conjunto feminino"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_duqbpeogkfl",
    titulo: "Vestido longo verde com estampa floral e fenda",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido longo verde com estampa floral, em tons de verde, branco e bege.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido longo verde com estampa floral por diferentes enquadramentos, com fenda frontal na saia, cordão para amarração na cintura.",
    imagens: ["instagram/DUqBPEOgKFL/01.webp", "instagram/DUqCAIvAJ54/01.webp"],
    palavras_chave: ["Vestidos", "verde", "branco", "vestido longo", "moda feminina", "estampa floral", "vestido verde", "plus size"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_duqcagtgkwi",
    titulo: "Vestido Longo Azul Teal com Fenda",
    categoria: "Vestidos",
    ambiente: "Não determinado",
    descricao_curta: "Vestido Longo com Fenda, em tons de dourado, azul teal e azul-petróleo.",
    descricao_comercial: "O conjunto de 2 imagens apresenta vestido longo com fenda por diferentes enquadramentos, com vestido longo de cor azul teal, fenda na altura da perna, vestido de cor azul-petróleo.",
    imagens: ["instagram/DUqCaGTgKWI/01.webp", "instagram/DUqCeZngM2Y/01.webp"],
    palavras_chave: ["Vestidos", "Dourado", "vestido longo", "moda feminina", "azul-petróleo", "Azul teal", "vestido azul", "fenda lateral"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_duqclmraoqu",
    titulo: "Macacão Longo Azul Claro com Faixa",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Longo, em tons de azul claro e branco.",
    descricao_comercial: "A imagem apresenta macacão longo, com peça única, alças finas, corte reto nas pernas e faixa na cintura.",
    imagens: ["instagram/DUqClMRAOQU/01.webp"],
    palavras_chave: ["Moda Feminina", "azul claro", "branco", "macacão", "macacão longo", "roupa azul", "plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_duqcnetgngu",
    titulo: "Macacão Feminino Longo Rosa Suave",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Feminino Longo, em tons de rosa e branco.",
    descricao_comercial: "A imagem apresenta macacão feminino longo, com peça única, cor rosa, alças largas e decote em v suave.",
    imagens: ["instagram/DUqCnetgNgU/01.webp"],
    palavras_chave: ["Moda Feminina", "rosa", "branco", "macacão", "plus size", "roupa feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_duqcpoygoje",
    titulo: "Macacão Longo Azul Claro Alças Largas",
    categoria: "Moda Feminina",
    ambiente: "Estúdio Fotográfico",
    descricao_curta: "Macacão Longo, para estúdio fotográfico, em tons de azul claro e branco.",
    descricao_comercial: "A imagem apresenta macacão longo, com peça única, alças largas, decote em formato v suave e corte longo nas pernas.",
    imagens: ["instagram/DUqCpoygOje/01.webp"],
    palavras_chave: ["Moda Feminina", "azul claro", "Estúdio Fotográfico", "branco", "macacão", "macacão longo", "plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_duqcuwian9j",
    titulo: "Macacão Curto Plus Size Verde Claro Decote Transpassado",
    categoria: "Moda Feminina",
    ambiente: "Externo",
    descricao_curta: "Macacão Curto Plus Size, para externo, em tons de dourado, verde claro e rosa.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macacão curto plus size por diferentes enquadramentos, com peça única com parte superior regata e decote em v cruzado, corte curto, faixa para amarrar na cintura.",
    imagens: ["instagram/DUqCUWIAN9j/01.webp", "instagram/DUqCYPmAHAj/01.webp"],
    palavras_chave: ["Moda Feminina", "Externo", "verde claro", "dourado", "plus size", "rosa", "macacão", "casual"],
    confidence: 0.9,
    needs_review: true
  },
  {
    id: "projeto_duqcwtfgd4s",
    titulo: "Macacão Curto Feminino Verde Claro",
    categoria: "Roupas Femininas",
    ambiente: "Externo",
    descricao_curta: "Macacão Curto Feminino, para externo, em tons de verde-claro, dourado e marrom.",
    descricao_comercial: "A imagem apresenta macacão curto feminino, com macacão curto de alças, detalhe franzido no busto, bolsa com superfície reflexiva e calçado de salto fino.",
    imagens: ["instagram/DUqCWTFgD4s/01.webp"],
    palavras_chave: ["Roupas Femininas", "Externo", "verde-claro", "dourado", "marrom", "macacão curto", "moda feminina", "plus size"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dvn8yr8gih1",
    titulo: "Conjunto de Blusa Drapeada e Shorts Laranja",
    categoria: "Roupas Femininas",
    ambiente: "Externo",
    descricao_curta: "Conjunto de Blusa e Shorts, para externo, em tons de branco, laranja e verde.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e shorts, com blusa de manga curta com decote arredondado e detalhe drapeado nas mangas, shorts com faixa para amarração na cintura.",
    imagens: ["instagram/DVn8YR8gIH1/01.webp"],
    palavras_chave: ["Roupas Femininas", "Externo", "branco", "laranja", "verde", "moda feminina", "plus size", "conjunto", "shorts laranja"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dw_rv1ujzjw",
    titulo: "Colete jeans sem mangas com bolsos",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Colete jeans sem mangas, em tons de azul, bege e dourado.",
    descricao_comercial: "A imagem apresenta colete jeans sem mangas, com fechamento frontal por botões, costuras pespontadas visíveis e bolsos superiores com lapela e botão.",
    imagens: ["instagram/DW_RV1UjZJW/01.webp"],
    palavras_chave: ["Roupas Femininas", "azul", "bege", "dourado", "colete", "jeans", "feminino", "sem mangas", "casual"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dwaukmvdier",
    titulo: "Conjunto de Blusa com Botões e Calça Bege",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Calça, em tons de beige e off-white.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e calça, com blusa com fechamento frontal por botões, calça de corte reto e conjunto monocromático.",
    imagens: ["instagram/DWaUKmVDIER/01.webp"],
    palavras_chave: ["Moda Feminina", "Beige", "Off-white", "conjunto feminino", "plus size", "calca reta"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dwaupx9dakb",
    titulo: "Macacão longo feminino pernas amplas",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Macacão longo feminino, em tons de branco, verde e amarelo.",
    descricao_comercial: "A imagem apresenta macacão longo feminino, com modelagem longa com pernas amplas, detalhe de debrum escuro no decote e nos bolsos, alças com presilhas visíveis.",
    imagens: ["instagram/DWaUPx9DAKb/01.webp"],
    palavras_chave: ["Roupas Femininas", "Branco", "Verde", "Amarelo", "Preto", "macacão", "macacão longo", "moda feminina"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dwauucrdiao",
    titulo: "Conjunto de Blusa Alças com Regulagem e Calça",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Calça, em tons de bege e off-white.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e calça, com blusa com fechamento frontal por botões, alças com regulagem, calça de cintura alta.",
    imagens: ["instagram/DWaUUCrDIao/01.webp"],
    palavras_chave: ["Moda Feminina", "Beige", "Off-white", "conjunto feminino", "plus size", "blusa", "calça"],
    confidence: 0.65,
    needs_review: true
  },
  {
    id: "projeto_dwav0mbdaxs",
    titulo: "Macacão estampado folhagens amarelo",
    categoria: "Moda Feminina",
    ambiente: "Loja de roupas",
    descricao_curta: "Macacão estampado, para loja de roupas, em tons de amarelo, rosa e laranja.",
    descricao_comercial: "A imagem apresenta macacão estampado, com macacão sem mangas com estampa de folhagens, cinto amarelo na mesma cor do fundo da estampa.",
    imagens: ["instagram/DWaV0mbDAxS/01.webp"],
    palavras_chave: ["Moda Feminina", "Loja de roupas", "amarelo", "rosa", "laranja", "preto", "macacão", "estampa de folhagens"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dwavty7jepe",
    titulo: "Macaquinho estampado floral fundo claro",
    categoria: "Moda Feminina",
    ambiente: "Loja física",
    descricao_curta: "Macaquinho estampado, para loja física, em tons de branco, marrom e rosa.",
    descricao_comercial: "O conjunto de 2 imagens apresenta macaquinho estampado por diferentes enquadramentos, com macaquinho de fundo branco com estampa marrom em formato de flores estilizadas.",
    imagens: ["instagram/DWaVTy7jEPe/01.webp", "instagram/DWaWBjCDDWS/01.webp"],
    palavras_chave: ["Moda Feminina", "branco", "marrom", "rosa", "macaquinho", "plus size", "Loja física", "estampa floral"],
    confidence: 1.0,
    needs_review: false
  },
  {
    id: "projeto_dwly9veggeb",
    titulo: "Macacão Longo Estampado Azul Escuro Linhas Curvas",
    categoria: "Moda Feminina",
    ambiente: "Não determinado",
    descricao_curta: "Macacão Longo Estampado, em tons de azul escuro, branco e preto.",
    descricao_comercial: "A imagem apresenta macacão longo estampado, com macacão longo sem mangas, decote em v, estampa abstrata de linhas curvas e corte reto nas pernas.",
    imagens: ["instagram/DWly9vegGEb/01.webp"],
    palavras_chave: ["Moda Feminina", "Azul escuro", "Branco", "Preto", "macacão", "macacão longo", "plus size", "estampado"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dwma7cwgj1p",
    titulo: "Jaqueta com textura felpuda e gola alta",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Jaqueta com textura felpuda, em tons de bege, marrom claro e preto.",
    descricao_comercial: "A imagem apresenta jaqueta com textura felpuda, com textura visual felpuda, gola alta, mangas longas com punhos franzidos e abertura frontal.",
    imagens: ["instagram/DWmA7cwgJ1P/01.webp"],
    palavras_chave: ["Roupas Femininas", "bege", "marrom claro", "preto", "jaqueta", "agasalho", "moda feminina", "textura felpuda"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dwoxiikafep",
    titulo: "Conjunto de Blusa e Calça Tons Terrosos Floral",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto de Blusa e Calça, em tons de marrom, mostarda e bege.",
    descricao_comercial: "A imagem apresenta conjunto de blusa e calça, com conjunto composto por blusa e calça na mesma estampa, estampa de linhas finas formando grandes flores estilizadas.",
    imagens: ["instagram/DWoXIIkAFep/01.webp"],
    palavras_chave: ["Roupas Femininas", "marrom", "mostarda", "bege", "conjunto", "blusa", "calça", "moda feminina", "estampa floral"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dwq3uvnafsy",
    titulo: "Calças femininas de superfície reflexiva cintura alta",
    categoria: "Calças",
    ambiente: "Não determinado",
    descricao_curta: "Calças femininas de superfície reflexiva, em tons de preto, marrom claro e marrom escuro.",
    descricao_comercial: "A imagem apresenta calças femininas de superfície reflexiva, com superfície reflexiva com brilho sutil, modelagem ajustada ao corpo, cintura alta e comprimento longo.",
    imagens: ["instagram/DWq3uVnAFSy/01.jpg"],
    palavras_chave: ["Calças", "preto", "marrom claro", "marrom escuro", "calça feminina", "cintura alta", "moda plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dwquljfdphm",
    titulo: "Macaquinho feminino pink decote V",
    categoria: "Roupas Femininas",
    ambiente: "Loja de Roupas",
    descricao_curta: "Macaquinho feminino pink, para loja de roupas, em tons de rosa, verde e preto.",
    descricao_comercial: "A imagem apresenta macaquinho feminino pink, com vestuário feminino de cor rosa vibrante, mangas curtas com detalhes vazados, decote em v.",
    imagens: ["instagram/DWquLjFDphM/01.webp"],
    palavras_chave: ["Roupas Femininas", "Loja de Roupas", "rosa", "verde", "preto", "moda feminina", "macaquinho", "roupa rosa", "plus size"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dygalcjjeim",
    titulo: "Conjunto Jeans Feminino Tomara que Caia",
    categoria: "Roupas Femininas",
    ambiente: "Não determinado",
    descricao_curta: "Conjunto Jeans Feminino, em tons de azul escuro, dourado e prata.",
    descricao_comercial: "A imagem apresenta conjunto jeans feminino, com top sem alças com costuras aparentes e calça de corte reto.",
    imagens: ["instagram/DYGalCJjEim/01.webp"],
    palavras_chave: ["Roupas Femininas", "azul escuro", "dourado", "prata", "conjunto feminino", "jeans", "moda plus size", "calça jeans"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dyibfqnj_0r",
    titulo: "Ambiente interno com decoração de balões rosa",
    categoria: "Ambiente Comercial",
    ambiente: "Interior de Loja",
    descricao_curta: "Ambiente interno com decoração de balões rosa, para interior de loja, em tons de rosa, branco e marrom.",
    descricao_comercial: "A imagem apresenta ambiente interno com decoração de balões rosa, com decoração com arcos de balões rosa, arranjo floral com rosas, piso de cerâmica e iluminação com lustre pendente.",
    imagens: ["instagram/DYIBFqNj-0R/01.webp"],
    palavras_chave: ["Ambiente Comercial", "rosa", "Interior de Loja", "branco", "marrom", "decoração com balões", "ambiente comercial"],
    confidence: 0.85,
    needs_review: false
  },
  {
    id: "projeto_dz_j0vhanaz",
    titulo: "Jaqueta Masculina com Capuz Acolchoada",
    categoria: "Moda Masculina",
    ambiente: "Não determinado",
    descricao_curta: "Jaqueta com Capuz, em tons de azul escuro e branco.",
    descricao_comercial: "A imagem apresenta jaqueta com capuz, com costuras horizontais acolchoadas, fechamento frontal por zíper, manga longa e presença de capuz.",
    imagens: ["instagram/DZ-J0VhANaz/01.webp"],
    palavras_chave: ["Moda Masculina", "Azul escuro", "Branco", "jaqueta", "casaco", "capuz", "plus size"],
    confidence: 0.85,
    needs_review: false
  }
];

// Write products.json
fs.writeFileSync(
  path.resolve('./src/data/products.json'),
  JSON.stringify(rawProducts, null, 2)
);

console.log(`Successfully generated products.json with ${rawProducts.length} items`);
